package-lock.json
package.json
src/App.js
src/Pages/Login/Login.jsx
src/hooks/useForm.js
src/services/user.jsx

:package:funcionalidade login

---

src/hooks/useRequestData.js

:package: useDataRequest

---

src/Pages/Cart/Cart.jsx
src/Pages/Feed/Feed.jsx
src/Pages/Login/Login.jsx
src/Pages/Profile/Profile.jsx
src/Pages/ShoppingDetail/ShoppingDetail.jsx
src/Pages/SignUp/SignUp.jsx

:beetle: correção de bug de rotas

---

src/Pages/Login/Login.jsx

:arrow_up: atualização ir pra cadastro

---

src/services/postServices.jsx
src/services/putServices.jsx

talvez tenha que fazer adequações nas linhas de retorno de reposta (sucesso ou erro).
as requisições solicitam input de parametros para serem executadas adequadamente.
atentar-se em enviar o body como objeto

:package: inserindo endpoints de post e put

---

src/Pages/Login/Login.jsx
src/Pages/SignUp/SignUp.jsx
src/Pages/SignUp/SignUpForm.jsx
src/Pages/SignUp/SignUpFormAdress.jsx_old
src/Pages/SignUpFormAdress/SignUpFormAdress.jsx
src/Pages/SignUpFormAdress/styled.js
src/routes/Router.js
src/routes/coordinator.js
src/services/user.jsx

:package:endereço

---

src/Pages/SignUpFormAdress/SignUpFormAdress.jsx
src/services/putServices.jsx

:package:adress 1

---

src/Pages/EditeProfile/EditeProfile.jsx
src/Pages/EditeProfile/styled.js
src/Pages/Profile/Profile.jsx
src/routes/Router.js
src/routes/coordinator.js
src/services/putServices.jsx

:package: aditar perfil

---

src/Pages/EditeProfile/styled.js
src/Pages/Profile/Profile.jsx
src/components/OrdersHistory/OrdersHistory.js
src/components/PersonalData.js/PersonalData.js
src/components/UserAdress/UserAdress.js

Izabella footer

---

src/Pages/Profile/Profile.jsx
src/components/UserAdress/UserAdress.js

:arrow_up: atualizando perfil

---

package-lock.json
package.json
src/Pages/Feed/Feed.jsx
src/Pages/Feed/style.jsx
src/components/Loading/Loading.jsx
src/components/Loading/style.jsx
src/components/RestaurantCard/RestaurantCard.jsx
src/components/RestaurantCard/style.jsx

também contém componente de loading

:package: implementaçao inicial do feed

---

src/Pages/Cart/Cart.jsx
src/Pages/EditeProfile/EditeProfile.jsx
src/Pages/Feed/Feed.jsx
src/Pages/Login/Login.jsx
src/Pages/Profile/Profile.jsx
src/Pages/ShoppingDetail/ShoppingDetail.jsx
src/Pages/SignUp/SignUp.jsx
src/Pages/SignUpFormAdress/SignUpFormAdress.jsx
src/components/Footer/Footer.js
src/components/Header/Header.js
src/components/Header/styled.js
src/components/PersonalData.js/PersonalData.js
src/components/UserAdress/UserAdress.js
src/routes/Router.js

:package: adicionando header e mudando cor de icones

---

src/routes/Router.js

:arrow_up: atualização router

---

src/Pages/Feed/Feed.jsx
src/Pages/Feed/style.jsx

para constar algumas atualizações da pag feed

atualização parcial da pag Feed

---

src/components/PersonalData.js/PersonalData.js
src/components/PersonalData.js/styled.js
src/components/UserAdress/UserAdress.js
src/components/UserAdress/styled.js
src/constants/colors.js

:art: estilizando perfil

---

public/index.html

:art: zerando margens e paddings

---

src/Pages/Profile/Profile.jsx
src/components/OrdersHistory/OrdersHistory.js
src/components/OrdersHistory/styled.js
src/components/PersonalData.js/PersonalData.js
src/components/UserAdress/UserAdress.js
src/components/UserAdress/styled.js
src/functions/functions.js

Izabella perfil

---

src/App.js
src/components/OrdersHistory/OrdersHistory.js
src/components/PersonalData.js/PersonalData.js
src/components/UserAdress/UserAdress.js
src/hooks/useRequestData.js

:beetle: corrigindo bug de data

---

src/App.js

:arrow_up: corrigindo app

---

package-lock.json
package.json
src/Pages/FeedSearch/FeedSearch.jsx
src/Pages/FeedSearch/style.jsx

Danilo pagina restaurante

---

public/index.html
src/Pages/Cart/Cart.css
src/Pages/Cart/Cart.jsx

:package:fonte Roboto

---

src/App.js
src/Pages/Cart/Cart.jsx
src/Pages/EditeProfile/styled.js
src/Pages/Feed/Feed.jsx
src/Pages/Feed/style.jsx
src/Pages/Login/Login.jsx
src/Pages/Login/styled.js
src/Pages/ShoppingDetail/ShoppingDetail.jsx
src/Pages/ShoppingDetail/styled.js
src/Pages/SignUp/SignUp.jsx
src/Pages/SignUp/styled.js
src/Pages/SignUpFormAdress/styled.js
src/components/Header/Header.js
src/components/Header/styled.js
src/routes/Router.js

:art: fixando header

---

src/Pages/Cart/Cart.jsx
src/components/Footer/Footer.js
src/components/Footer/styled.js

:beetle: corrigindo aparecimento de active order

---

src/components/Footer/Footer.js

:beetle: resolvendo problema de estilização no footer

---

src/components/OrdersHistory/OrdersHistory.js

:arrow_up: atualizando informação do his´torico de pedidos

---

src/Pages/ShoppingDetail/AddCart/AddCartd.js
src/Pages/ShoppingDetail/CardProduct/CardProduct.js
src/Pages/ShoppingDetail/ShoppingDetail.jsx

Vitoria remover

---

src/Pages/Cart/Cart.jsx
src/components/ActiveOrder/ActiveOrder.js

:package:map carrinho

---

src/App.js
src/Pages/Cart/Cart.jsx
src/Pages/EditeProfile/EditAddress.jsx
src/Pages/EditeProfile/EditeProfile.jsx
src/Pages/Feed/Feed.jsx
src/Pages/FeedSearch/FeedSearch.jsx
src/Pages/Login/Login.jsx
src/Pages/Profile/Profile.jsx
src/Pages/ShoppingDetail/ShoppingDetail.jsx
src/Pages/SignUp/SignUp.jsx
src/Pages/SignUpFormAdress/SignUpFormAdress.jsx
src/components/Footer/Footer.js
src/components/Footer/styled.js
src/components/Header/Header.js
src/constants/theme.js
src/global/GlobalState.js
src/routes/Router.js

Atualizando header

---

src/Pages/ShoppingDetail/AddCart/AddCartd.js
src/Pages/ShoppingDetail/CardProduct/CardProduct.js
src/Pages/ShoppingDetail/ShoppingDetail.jsx

Vitoria logica não permite dois restautes carrinho

---

src/Pages/Cart/Cart.jsx
src/Pages/ShoppingDetail/ShoppingDetail.jsx

:package:carCerto

---

src/Pages/ShoppingDetail/ShoppingDetail.jsx

:arrow_up: Funcionalidade de loading da página de restaurantes

---

src/Pages/Cart/Cart.jsx

Pimentel12

---

src/Pages/Cart/Cart.css

:package: estilizacao

---

src/Pages/Cart/Cart.jsx
src/Pages/ShoppingDetail/ShoppingDetail.jsx
src/Pages/SignUpFormAdress/SignUpFormAdress.jsx
src/components/ActiveOrder/ActiveOrder.js
src/components/Footer/Footer.js
src/components/RestaurantCard/RestaurantCard.jsx
src/components/RestaurantCard/style.jsx
src/services/postServices.jsx
src/services/user.jsx

:arrow_up: atualizacao imagens card

---

README.md

:arrow_up: atualizando readme

---

README.md

arrow_up: atualizando readme

---

src/Pages/Login/LoginForm.jsx
src/Pages/SignUp/SignUpForm.jsx
src/components/Input/Input.js

Thais form password

---

src/Pages/Cart/Cart.jsx
src/Pages/Login/Login.jsx
src/Pages/Profile/Profile.jsx
src/Pages/SignUpFormAdress/SignUpFormAdress.jsx
src/hooks/useRequestData.js

useDataRequest agora retorna vazio quando está sem token, dessa os componentes que fazem requisição antes do usuario estar logado não fornecem alerta de erro na tela inicial

Danilo revisao bug

---

src/Pages/EditeProfile/EditeProfile.jsx
src/components/PersonalData.js/PersonalData.js
src/components/UserAdress/UserAdress.js

:beetle: correção de bug perfil

---

src/Pages/SignUp/SignUpForm.jsx

:beetle: Validação senhas

---

src/Pages/Cart/Cart.jsx
src/Pages/EditeProfile/EditAddress.jsx
src/Pages/EditeProfile/EditeProfile.jsx
src/Pages/Profile/Profile.jsx
src/components/ActiveOrder/ActiveOrder.js
src/global/GlobalState.js
src/services/postServices.jsx

:beetle: corrigindo bug activeOrder

---

src/Pages/SignUpFormAdress/SignUpFormAdress.jsx
src/Pages/SignUpFormAdress/styled.js

:beetle: correção de bug cadastrar enedereço

---

src/Pages/EditeProfile/EditAddress.jsx
src/Pages/EditeProfile/EditeProfile.jsx
src/components/FormEditAddress/FormEditAddress.jsx
src/components/FormEditAddress/styled.js
src/components/FormEditPersonalData.jsx
src/components/UserAdress/UserAdress.js
src/global/GlobalState.js

:beetle: corrigindo bug perfil
